---
- name: install docker & docker compose on ubuntu and centos
  hosts: all
  become: yes

  tasks:
    #- name: install nginx on centos
    #  yum: 
    #      name=nginx 
    #     state=latest
    #  notify:
    #    - reload service firewalld   
    #    - edit-firewall
    #  when: ansible_os_family == "RedHat"

#    - name: install docker on ubuntu
#      apt: 
#          name=nginx 
#          state=latest
 #     when: ansible_os_family == "Debian"

  - name: Install yum utils
    yum:
        name: yum-utils
        state: latest
 
  - name: Add Docker repo
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker
    yum:
        name: docker-ce
        state: latest

  - name: Install Docker-ce-cli
    yum:
        name: docker-ce-cli
        state: latest

  - name: Install containerd.io
    yum:
        name: containerd.io
        state: latest

  - name: Start Docker service
    service:
        name: docker
        state: started
        enabled: yes      



  - name: "Update Repository cache (Debian)"
    apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    when: ansible_os_family == "Debian"    
      
  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]
    when: ansible_os_family == "Debian"

  - name: Add Docker GPG apt Key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    when: ansible_os_family == "Debian"    

  - name: Add Docker Repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    when: ansible_os_family == "Debian"    

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
    when: ansible_os_family == "Debian"

  - name: Update apt and install docker-ce-cli
    apt: update_cache=yes name=docker-ce-cli state=latest
    when: ansible_os_family == "Debian"

  - name: Update apt and install containerd.io 
    apt: update_cache=yes name=containerd.io state=latest
    when: ansible_os_family == "Debian"
 
  - name: Install docker-compose from official github repo
    get_url:
       url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
       dest: /usr/local/bin/docker-compose
       mode: 'u+x,g+x'