---
# tasks file for inst-adminer-mysql-balans

- name: start adminer-docker No1
  docker_container:
    name: myadmier1
    image: adminer
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports:
    - "88:8080"
    env: 
      ADMINER_DESIGN: "nette"
   
- name: start adminer-docker No2
  docker_container:
    name: myadmier2
    image: adminer
    state: started
    restart_policy: unless-stopped
    restart: yes
    ports:
    - "89:8080"
    env: 
      ADMINER_DESIGN: "dracula"

- name: start adminer-docker No3
  docker_container:
    name: myadmier3
    image: adminer
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports:
    - "90:8080"    
    env: 
      ADMINER_DESIGN: "lucas-sandery"

- name: mkdir etc/fornginx
  file:
     path: '{{item}}'
     state: directory
     mode: '0775'
  loop: 
     - /etc/fornginx/conf
     - /etc/fornginx/cert

- name: copy configuration file for nginx
  copy:
     src: ./inst-adminer-mysql-balans/files/default.conf 
     dest: /etc/fornginx/conf/default.conf
     force: yes

- name: copy ssl certificates for nginx
  copy:
     src: '{{item}}'
     dest: /etc/fornginx/cert/
     force: yes
  loop:
    - ./inst-adminer-mysql-balans/files/fullchain1.pem
    - ./inst-adminer-mysql-balans/files/privkey1.pem
  
- name: start nginx-docker + mount dir with my config
  docker_container:
    name: mynginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    restart: yes
    ports:
    - "443:443"   
    volumes:
       - /etc/fornginx/conf:/etc/nginx/conf.d
       - /etc/fornginx/cert:/etc/nginx/cert