---
#- name: tasks file for nginx-src-inst
  
  # Block for ubuntu  
  - block: 
     - name: Update Repository cache ubuntu
       apt:
          update_cache: true
          cache_valid_time: 3600
          force_apt_get: true

     - name: install development libraries #Nginx Web Server for Ubuntu
       apt: 
         pkg:
          - build-essential
          - libpcre3
          - libpcre3-dev  
          - zlib1g 
          - zlib1g-dev 
          - libssl-dev 
          - libgd-dev 
          - libxml2 
          - libxml2-dev 
          - uuid-dev
         state: latest
    when: ansible_os_family == "Debian"

 # Block for centos
  - block:
     - name: Upgrade all packages
       yum:
          name: '*'
          state: latest

     - name: install development libraries #for Centos
       yum: 
         name:
          - gcc
          - libverto-devel
          - zlib-devel
          - openssl-devel
          - make 
          - pcre-devel
          - libxml2-devel
          - libxslt-devel
          - libgcrypt-devel
          - gd-devel
          - perl-ExtUtils-Embed
          - epel-release
          - GeoIP-devel
         state: latest
   
    when: ansible_os_family == "RedHat"


  - name: mkdir /etc/tempnginx
    file:
       path: /etc/tempnginx
       state: directory
       mode: '0775'

  - name: download and unarchive NGINX Source Code
    unarchive:
       src: http://nginx.org/download/nginx-1.21.6.tar.gz
       dest: /etc/tempnginx
       remote_src: yes
    
  - name: Run a script for configuring NGINX
    command: ./configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic --modules-path=/etc/nginx/modules --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module 
    args:
        chdir: /etc/tempnginx/nginx-1.21.6/ 
  
  - name: Run 'make' - compile NGINX source code
    make:
      chdir: /etc/tempnginx/nginx-1.21.6/

  - name: Run 'make' - install the compiled source code
    make:
      chdir: /etc/tempnginx/nginx-1.21.6/
      target: install

  # Block for centos
  - block:
    - name: edit-firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
    
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    when: ansible_os_family == "RedHat"           


  - name: copy unit file
    copy: 
      src: ./nginx-src-inst/files/nginx-1.21.6.service
      dest: /etc/systemd/system/

  - name: copy environment file 
    copy: 
      src: ./nginx-src-inst/files/nginx-1.21.6
      dest: /etc/sysconfig/   


  - name: "Start nginx"
    systemd: 
           name: nginx-1.21.6 
           state: started
           enabled: yes    # why?