---
- name: tasks file for nginx-src-inst
  
  block: # Block for ubuntu
   - name: Update Repository cache ubuntu
     apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

   - name: install development libraries #Nginx Web Server for Ubuntu
     apt: 
       pkg:
       - build-essential
       - libpcre3
       - libpcre3-dev  
       - zlib1g 
       - zlib1g-dev 
       - libssl-dev 
       - libgd-dev 
       - libxml2 
       - libxml2-dev 
       - uuid-dev
       state: latest
  when: ansible_os_family == "Debian"

- name: mkdir /home/sergey/tempnginx
  file:
    path: /home/sergey/tempnginx
    state: directory
    mode: '0775'

- name: download and unarchive NGINX Source Code
  unarchive:
    src: http://nginx.org/download/nginx-1.21.6.tar.gz
    dest: /home/sergey/tempnginx
    remote_src: yes
    
- name: Run a script for configuring NGINX
  command: ./configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic --modules-path=/etc/nginx/modules --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module 
    
  args:
     chdir: /home/sergey/tempnginx/nginx-1.21.6/ 
  
- name: Run 'make' - compile NGINX source code
  make:
    chdir: /home/sergey/tempnginx/nginx-1.21.6/

- name: Run 'make' - install the compiled source code
  make:
    chdir: /home/sergey/tempnginx/nginx-1.21.6/
    target: install

- name: Run NGINX
  command: nginx   








# - name: "Start nginx"
#   systemd: 
#            name: nginx 
#            state: started
#            enabled: yes    # why?