FROM ubuntu:latest

RUN apt-get update && apt-get install apache2 php php-curl libapache2-mod-php php-cli php-mysql php-gd mariadb-server -y

RUN apt-get update && apt-get install httpd && && apt-get install -y adminer

EXPOSE 80