apiVersion: v1
kind: Namespace
metadata:
  name: hw53p1
  labels:
    name: hw53p1
---
apiVersion: v1
kind: Pod
metadata:
  name: hw53p1memcpu
  namespace: hw53p1
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"